// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DaytonaSandboxProviderAuth } from "./DaytonaSandboxProviderAuth.js";

export const SandboxProviderManifest: core.serialization.ObjectSchema<
    serializers.SandboxProviderManifest.Raw,
    TrueForge.SandboxProviderManifest
> = core.serialization.object({
    auth: DaytonaSandboxProviderAuth.optional(),
    autoArchiveIntervalInMinutes: core.serialization.property(
        "auto_archive_interval_in_minutes",
        core.serialization.number().optional(),
    ),
    autoDeleteIntervalInMinutes: core.serialization.property(
        "auto_delete_interval_in_minutes",
        core.serialization.number().optional(),
    ),
    autoStopIntervalInMinutes: core.serialization.property(
        "auto_stop_interval_in_minutes",
        core.serialization.number().optional(),
    ),
    execTimeoutMs: core.serialization.property("exec_timeout_ms", core.serialization.number()),
    type: core.serialization.string(),
});

export declare namespace SandboxProviderManifest {
    export interface Raw {
        auth?: DaytonaSandboxProviderAuth.Raw | null;
        auto_archive_interval_in_minutes?: number | null;
        auto_delete_interval_in_minutes?: number | null;
        auto_stop_interval_in_minutes?: number | null;
        exec_timeout_ms: number;
        type: string;
    }
}
